[project]
authors = ["Martin Lange <martin_lange_@gmx.net>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Minmal ECS"
name = "minecs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.2.0.dev2025021505"
